# -*- coding: utf-8 -*-
"""
Created on Sat Oct 17 19:46:42 2020

@author: Brian
"""

import turtle

def main():
    print("Would you like to build a snowman?")
    drawBase()

def drawBase():
    turtle.bgcolor('lightblue')
    turtle.penup()
    turtle.goto(0, -150)    
    turtle.pendown()
    turtle.circle(80)
    drawMidSection()
    
def drawMidSection():
    turtle.penup()
    turtle.left(90)
    turtle.forward(160)
    turtle.right(90)
    turtle.pendown()
    turtle.circle(60)
    drawArms()
    
def drawArms():
    turtle.penup()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(60)
    turtle.left(30)
    turtle.pendown()
    turtle.forward(60)
    turtle.left(30)
    turtle.forward(30)
    turtle.right(180)
    turtle.forward(30)
    turtle.left(120)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.left(30)
    turtle.forward(60)
    turtle.right(30)
    turtle.penup()
    turtle.forward(120)
    turtle.pendown()
    turtle.right(20)
    turtle.forward(40)
    turtle.right(40)
    turtle.forward(30)
    turtle.left(30)
    turtle.forward(30)
    turtle.right(180)
    turtle.forward(30)
    turtle.left(120)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.left(30)
    turtle.forward(30)
    turtle.left(40)
    turtle.forward(40)
    turtle.penup()
    turtle.forward(60)
    turtle.left(116)
    turtle.forward(82)
    drawHead()

def drawHead():
    turtle.right(110)
    turtle.pendown()
    turtle.circle(40)
    turtle.penup()
    turtle.left(100)
    turtle.forward(50)
    turtle.pendown()
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.circle(5)
    turtle.penup()
    turtle.right(100)
    turtle.forward(20)
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.forward(10)
    turtle.right(80)
    turtle.forward(10)
    turtle.right(86)
    turtle.pendown()
    turtle.forward(50)
    turtle.penup()
    turtle.right(90)
    turtle.forward(30)
    drawHat()
    
def drawHat():
    turtle.right(90)
    turtle.pendown()
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(30)
    turtle.end_fill()
    drawCoal()
    
def drawCoal():
    turtle.penup()
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(85)
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(10)
    turtle.penup()
    turtle.forward(38)
    turtle.pendown()
    turtle.circle(10)
    turtle.penup()
    turtle.forward(38)
    turtle.pendown()
    turtle.circle(10)
    turtle.end_fill()
    turtle.hideturtle()
    turtle.done()
    
main()